version: "3"

services:
  postgres-db:
    image: postgres:10.4
    volumes:
      - /var/db/data/postgresql:/var/lib/postgresql
    ports:
      - 5432:5432
    restart: unless-stopped
    networks:
      - net
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: planner-db
    container_name: postgres-db

  adminer:
    image: adminer
    restart: always
    ports:
      - 9090:8080
    depends_on:
      - postgres-db
    links:
      - postgres-db
    networks:
      - net
    container_name: adminer

  planner-frontend:
    build: ./planner-frontend
    image: planner/react-ui
#    volumes:
#      - '/planner-frontend:/app'
#      - '/app/node_modules'
#      - '/app/package.json'
    ports:
      - 3000:80
#    environment:
#      - CHOKIDAR_USEPOLLING=true
    container_name: react-ui

networks:
  net:
    driver: bridge

